name: continuous-integration
on:
  - push
jobs:

  test:
    runs-on: ubuntu-latest
    steps:

      - name: Check-out code
        uses: actions/checkout@v2

      - name: Install Ruby
        uses: actions/setup-ruby@v1

      - name: Install dependencies
        run: bundle install

      - name: Run unit tests
        run: bundle exec rspec --format documentation

      - name: Test packaging
        run: bundle exec gem build databricks.gemspec

  semantic_release:
    needs: test
    runs-on: ubuntu-latest
    steps:

      - name: Check-out code
        uses: actions/checkout@v2

      - name: Install Ruby
        uses: actions/setup-ruby@v1

      - name: Install Node
        uses: actions/setup-node@v2

      - name: Install semantic-release
        run: npm install @semantic-release/git @semantic-release/changelog @semantic-release/exec semantic-release-rubygem -D

      - name: Install dependencies
        run: bundle install

      - name: Semantic releasing
        run: npx semantic-release
        env:
          GEM_HOST_API_KEY: ${{secrets.GEM_HOST_API_KEY}}
